# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: api-build-deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  artifact-name: web-api
  artifact-path: "artefacts/web-api"
  artifact-publish-folder: "../../.."
  version: "9.0.x"
  working-directory: "src/back/GenAIChat"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Call build-back workflow
        uses: ./.github/workflows/build-back.yml
        with:
          artifact-name: ${{ env.artifact-name }}
          artifact-path: ${{ env.artifact-path }}
          artifact-publish-folder: ${{ env.artifact-publish-folder }}
          version: ${{ env.version }}
          working-directory: ${{ env.working-directory }}

  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  environment: production
  #  steps:
  #    - name: Call deploy-back workflow
  #      uses: ./.github/workflows/base/deploy-back.yml
  #      with:
  #        ARTIFACT: ${{ env.build_artifact }}
  #        DOTNET_VERSION: ${{ env.build_version }}
  #        SOURCE: ${{ env.build_source }}
  #        TARGET: ${{ env.build_target }}
