name: api-build-deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-back:
    uses: BoobaFetes/gemini-chat/.github/workflows/build-back.yml@feat-set-workflow-template
    with:
      artifact-name: web-api
      artifact-path: "artefacts/web-api"
      artifact-publish-folder: "../../.."
      version: "9.0.x"
      working-directory: "src/back/GenAIChat"
  deploy-back:
    needs: build-back
    uses: BoobaFetes/gemini-chat/.github/workflows/deploy-azure-web-api.yml@feat-set-workflow-template
    with:
      artifact-name: web-api
      azure-webapp-name: "gemini-chat-web-app"
      azure-webapp-package-path: "."
      AZURE_CREDENTIALS: ${{ vars.AZURE_CREDENTIALS_VAR }}
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
