# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: api-build-deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: BoobaFetes/gemini-chat/.github/workflows/build-back.yml@feat-set-workflow-template
    with:
      artifact-name: web-api
      artifact-path: "artefacts/web-api"
      artifact-publish-folder: "../../.."
      version: "9.0.x"
      working-directory: "src/back/GenAIChat"
  deploy:
    needs: build
    uses: BoobaFetes/gemini-chat/.github/workflows/deploy-back-on-azure-web-api.yml@feat-set-workflow-template
    with:
      artifact-name: web-api
      azure-webapp-name: "gemini-chat-web-app"
      azure-webapp-package-path: "."
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
