# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-front

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "The name of the artefact to deploy"
        type: string
        required: true
      artifact-path:
        description: "The path to the artefact"
        type: string
        required: true
      artifact-publish-folder:
        description: "The path to the artefact from the working directory, it allow to navigate throught the folders to find the root of the project"
        type: string
        default: "."
      version:
        description: "The version of dotnet to use"
        type: string
        required: true
      working-directory:
        description: "The path to the working directory"
        type: string
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up node environement and use yarn as cache for faster builds
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.version }}

      - name: install npm packages
        run: yarn
        working-directory: ${{ inputs.working-directory }}

      # aucun tests pour le moment => - name: test
      # aucun tests pour le moment =>   run: yarn nx run client:test
      # aucun tests pour le moment =>   working-directory: ${{ inputs.working-directory }}

      - name: build
        run: yarn nx run client:build
        working-directory: ${{ inputs.working-directory }}

      - name: Create artefacts directory
        run: mkdir -p ${{ inputs.artifact-path }}

      - name: move dest to artefacts folder
        working-directory: ${{ inputs.working-directory }}
        run: mv dist/apps/client/* ${{ inputs.artifact-publish-folder }}/${{ inputs.artifact-path }}

      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
