# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-back

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  DOTNET_VERSION: "9.0.x"
  SOURCE: "src/back/GenAIChat"
  TARGET: "artefacts/back"
  EXPORT: back-app

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up dotnet environement
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dotnet dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ env.DOTNET_VERSION }}

      - name: install nugget packages
        run: dotnet restore
        working-directory: ${{ env.SOURCE }}

      - name: build
        run: dotnet build --no-restore
        working-directory: ${{ env.SOURCE }}

      - name: test
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.SOURCE }}

      - name: publish
        run: dotnet publish -c Release -o ../../../${{ env.TARGET }}
        working-directory: ${{ env.SOURCE }}

      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT }}
          path: ${{ env.TARGET }}
