# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-front

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

env:
  NODE_VERSION: "latest"
  SOURCE: "src/front"
  TARGET: "artefacts/front"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set location to "src/front"
        run: cd src/front

      - name: Set up node environement and use yarn as cache for faster builds
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          working-directory: ${{ env.SOURCE }}

      - name: install npm packages
        run: yarn

      - name: test
        run: yarn test

      - name: build
        run: yarn build

      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: front-app
          path: ${{ env.TARGET }}
