# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-front

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

env:
  NODE_VERSION: "latest"
  SOURCE: "src/front"
  TARGET: "artefacts/front"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node environement and use yarn as cache for faster builds
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: ${{ env.SOURCE }}

      - name: install npm packages
        run: yarn
        working-directory: ${{ env.SOURCE }}

      # aucun tests pour le moment => - name: test
      # aucun tests pour le moment =>   run: yarn nx run client:test
      # aucun tests pour le moment =>   working-directory: ${{ env.SOURCE }}

      - name: build
        run: yarn nx run client:build:production
        working-directory: ${{ env.SOURCE }}

      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: front-app
          path: ${{ env.TARGET }}
