# This workflow will build a .NET and a webpack projects and is made from "Deploy a .NET Core app to an Azure Web App" template
# see templates here: https://github.com/BoobaFetes/gemini-chat/actions/new
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PR-build-front

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]

env:
  artifact-name: "PR-browser-app"
  artifact-path: "artefacts/PR-browser-app"
  artifact-publish-folder: "../.."
  version: "latest"
  working-directory: "src/front"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Set up node environement and use yarn as cache for faster builds
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.version }}

      - name: install npm packages
        run: yarn
        working-directory: ${{ env.working-directory }}

      # aucun tests pour le moment => - name: test
      # aucun tests pour le moment =>   run: yarn nx run client:test
      # aucun tests pour le moment =>   working-directory: ${{ env.working-directory }}

      - name: build
        run: yarn nx run client:build
        working-directory: ${{ env.working-directory }}

      - name: Create artefacts directory
        run: mkdir -p ${{ env.artifact-path }}

      - name: move dest to artefacts folder
        working-directory: ${{ env.working-directory }}
        run: mv dist/apps/client/* ${{ env.artifact-publish-folder }}/${{ env.artifact-path }}

      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.artifact-path }}
