name: project-deploy

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Nom de la branche à utiliser"
        required: true
        type: string
        default: "main"
  push:
    branches: ["main"]

jobs:
  build:
    uses: BoobaFetes/gemini-chat/.github/workflows/project-build.yml@${{ github.event.inputs.branch-name }}
    with:
      branch-name: ${{ github.event.inputs.branch-name }}

  azure:
    needs: [build]
    uses: BoobaFetes/gemini-chat/.github/workflows/deploy-on-azure.yml@${{ github.event.inputs.branch-name }}
    with:
      artifact-back-name: web-api
      artifact-front-name: web-client
      azure-webapp-name: "gemini-chat-web-app"
      azure-webapp-package-path: "."
    secrets: inherit
