name: project-deploy

on:
  pull_request:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Nom de la branche à utiliser"
        required: true
        type: string
        default: "main"
  push:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/project-build.yml
    secrets: inherit

  azure:
    needs: [build]
    uses: ./.github/workflows/deploy-on-azure.yml
    with:
      artifact-back-name: web-api
      artifact-front-name: web-client
      azure-webapp-name: "gemini-chat-web-app"
      azure-webapp-package-path: "."
    secrets: inherit
