name: project-deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  # front:
  #   uses: BoobaFetes/gemini-chat/.github/workflows/build-front.yml@main
  #   with:
  #     artifact-name: web-client
  #     version: "latest"
  #     working-directory: "src/front"

  back:
    uses: BoobaFetes/gemini-chat/.github/workflows/build-back.yml@feat-add-secrets
    with:
      artifact-name: web-api
      version: "9.0.x"
      working-directory: "src/back/GenAIChat/GenAIChat.Presentation.API"

  # azure:
  #   needs: [front, back]
  #   uses: BoobaFetes/gemini-chat/.github/workflows/deploy-on-azure.yml@main
  #   with:
  #     artifact-back-name: web-api
  #     artifact-front-name: web-client
  #     azure-webapp-name: "gemini-chat-web-app"
  #     azure-webapp-package-path: "."
  #   secrets: inherit
