name: project-deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/project-build.yml
    secrets: inherit

  azure:
    needs: [build]
    uses: ./.github/workflows/deploy-on-azure.yml
    with:
      artifact-back-name: web-api-${{ github.ref }}-${{ github.head_ref }}
      artifact-front-name: web-client-${{ github.ref }}-${{ github.head_ref }}
      azure-webapp-name: "gemini-chat-web-app"
      azure-webapp-package-path: "."
    secrets: inherit
