name: Mon Workflow avec Secret sur PR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  mon_job:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le secret
        run: echo "${{ secrets.MON_SECRET }}"
